In [29]:
import numpy as np


sales = np.array([
    [50000, 30000, 20000, 10000],  
    [52000, 32000, 21000, 12000],  
    [48000, 31000, 19000, 11000],  
    [60000, 35000, 25000, 15000],  
    [58000, 34000, 24000, 14000],  
    [62000, 36000, 26000, 16000],  
    [65000, 38000, 27000, 17000],  
    [64000, 37000, 26500, 16500],  
    [63000, 36500, 25500, 15500],  
    [67000, 39000, 28000, 18000],  
    [69000, 40000, 29000, 19000],  
    [72000, 42000, 30000, 20000]   
])

months = np.array([
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
])

products = np.array(["Laptop", "Phone", "Tablet", "Headphones"])

print("Sales Data:\n", sales)

# 1. Total sales of all products for the year
total_sales = np.sum(sales)
print("\nTotal Yearly Sales:", total_sales)

# 2. Total sales for each product
product_sales = np.sum(sales, axis=0)
print("\nTotal Sales by Product:")
for product, value in zip(products, product_sales):
    print(product, ":", value)

# 3. Total sales for each month
monthly_sales = np.sum(sales, axis=1)
print("\nTotal Sales by Month:")
for month, value in zip(months, monthly_sales):
    print(month, ":", value)

# 4. Average sales
average_sales = np.mean(sales)
print("\nAverage Sales:", average_sales)

# 5. Highest and lowest single sales value
max_sale = np.max(sales)
min_sale = np.min(sales)
print("\nHighest Sale Value:", max_sale)
print("Lowest Sale Value:", min_sale)

# 6. Best performing product
best_product_index = np.argmax(product_sales)
print("\nBest Performing Product:", products[best_product_index])

# 7. Best sales month
best_month_index = np.argmax(monthly_sales)
print("Best Sales Month:", months[best_month_index])

# 8. Sales greater than 30000
high_sales = sales[sales > 30000]
print("\nSales values greater than 30000:\n", high_sales)

# 9. Product with lowest yearly sales
lowest_product_index = np.argmin(product_sales)
print("\nLowest Performing Product:", products[lowest_product_index])

# 10. Monthly average sales
monthly_avg = np.mean(sales, axis=1)
print("\nMonthly Average Sales:")
for month, value in zip(months, monthly_avg):
    print(month, ":", value)

Sales Data:
 [[50000 30000 20000 10000]
 [52000 32000 21000 12000]
 [48000 31000 19000 11000]
 [60000 35000 25000 15000]
 [58000 34000 24000 14000]
 [62000 36000 26000 16000]
 [65000 38000 27000 17000]
 [64000 37000 26500 16500]
 [63000 36500 25500 15500]
 [67000 39000 28000 18000]
 [69000 40000 29000 19000]
 [72000 42000 30000 20000]]

Total Yearly Sales: 1645500

Total Sales by Product:
Laptop : 730000
Phone : 430500
Tablet : 301000
Headphones : 184000

Total Sales by Month:
Jan : 110000
Feb : 117000
Mar : 109000
Apr : 135000
May : 130000
Jun : 140000
Jul : 147000
Aug : 144000
Sep : 140500
Oct : 152000
Nov : 157000
Dec : 164000

Average Sales: 34281.25

Highest Sale Value: 72000
Lowest Sale Value: 10000

Best Performing Product: Laptop
Best Sales Month: Dec

Sales values greater than 30000:
 [50000 52000 32000 48000 31000 60000 35000 58000 34000 62000 36000 65000
 38000 64000 37000 63000 36500 67000 39000 69000 40000 72000 42000]

Lowest Performing Product: Headphones

Monthly Averag